---

druid:
  master:
    coordinator:
      jvm: |
        -server
        -Xms1g
        -Xmx1g
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseG1GC
        -Duser.timezone=UTC
        -Dfile.encoding=UTF-8
        -Djava.io.tmpdir={{ druid_tmpdir }}
        -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
        -Dderby.stream.error.file={{ druid_log_dir }}/derby.log

      properties: |
        druid.service=druid/coordinator
        druid.plaintextPort=8081

        druid.coordinator.startDelay=PT10S
        druid.coordinator.period=PT5S

        # Run the overlord service in the coordinator process
        #druid.coordinator.asOverlord.enabled=true
        #druid.coordinator.asOverlord.overlordService=druid/overlord

        druid.indexer.queue.startDelay=PT5S

        druid.indexer.runner.type=remote
        druid.indexer.storage.type=metadata

    overlord:
      jvm: |
        -server
        -Xms1g
        -Xmx1g
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseG1GC
        -Duser.timezone=UTC
        -Dfile.encoding=UTF-8
        -Djava.io.tmpdir={{ druid_tmpdir }}
        -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
        -Dderby.stream.error.file={{ druid_log_dir }}/derby.log

      properties: |
        druid.service=druid/overlord
        druid.plaintextPort=8090

        druid.coordinator.startDelay=PT10S
        druid.coordinator.period=PT5S

        druid.indexer.queue.startDelay=PT5S

        druid.indexer.runner.type=remote
        druid.indexer.storage.type=metadata

