---

- name: "Copy druid systemd services for {{ services }} to /etc/systemd/system/"
  template:
    src: "systemd/druid-{{ item.name }}.service.j2"
    dest: "/etc/systemd/system/druid-{{ item.name }}.service"
  with_items:
  - "{{ _services }}"
  notify: Restart druid services
