---

- hosts: all
  vars_files:
  - "../group_vars/all.yml"
  - "../group_vars/druid-master.yml"
  - "../group_vars/druid-data.yml"
  - "../group_vars/druid-query.yml"
  roles:
    - jdk
    - druid/common

- hosts: postgresql
  vars_files:
  - "../group_vars/all.yml"
  roles:
    - { role: postgresql, when: db_uri is match(".*postgresql.*") }

- hosts: zookeeper
  vars_files:
  - "../group_vars/all.yml"
  roles:
    - zookeeper
 
- hosts: master
  vars_files:
  - "../group_vars/all.yml"
  - "../group_vars/druid-master.yml"
  - "../group_vars/druid-data.yml"
  - "../group_vars/druid-query.yml"
  roles:
    - { role: "druid/services", vars: [ services : ["overlord", "coordinator"] ] }

- hosts: data
  vars_files:
  - "../group_vars/all.yml"
  - "../group_vars/druid-master.yml"
  - "../group_vars/druid-data.yml"
  - "../group_vars/druid-query.yml"
  roles:
     - { role: "druid/services", vars: [ services : ["historical", "middleManager"] ] }

- hosts: query
  vars_files:
  - "../group_vars/all.yml"
  - "../group_vars/druid-master.yml"
  - "../group_vars/druid-data.yml"
  - "../group_vars/druid-query.yml"
  roles:
    - { role: "druid/services", vars: [ services : ["broker", "router"] ] }


